### ISSUE TITLE
Ontwikkel omgeving

### ISSUE THREAD

**Issue by mylene** [mylene/Alphabet#1]
* IMHO is er geen reden om één development environment te kiezen.
* Wat dan wel moet gebeuren is dat er gezorgd wordt dat overal en altijd een vaste layout wordt doorgevoerd (tabs / spaties, aantal, lengte regel, waar regelovergang...), dat soort
* Volgens mij is daar tooling voor --> **uitzoeken**
* Ik heb een zware voorkeur voor JUnit voor Unit Testing, maar ik denk dat we TestNG moeten meenemen i.v.m. mogelijkheden parallel draaien --> **uitzoeken**
* Voor eerste iteratie toch maar Maven?
* Configuratie komt later (zie volgende issues, als daarvoor iets te configureren valt...). --> **uitzoeken** nut van [https://github.com/typesafehub/config]

[https://github.com/typesafehub/config]: https://github.com/typesafehub/config

**Comment by mylene** [comment]
Heb zitten kijken naar code beautifiers, maar er zijn blijbaar geen recente. ==> ** kijken wat we daamee doen **

**Comment by DominiqueClaes** [comment]
Indien IntelliJ de IDE wordt, dan is er, denk ik, een mogelijkheid om een code template in te stellen. Op basis van zo een template kunnen we enkele dingen afdwingen.
