### ISSUE TITLE
SCM

### ISSUE THREAD

**Issue by mylene** [mylene/Alphabet#2]
Mijn voorkeur gaat uit naar Git, voorlopig voor dit project GitHub kiezen, en verder kijken in volgende iteraties? **beslissen of alternatief kiezen**.

**Comment by yuri-vlieks** [comment]
Is het bij het uitzoeken van belang om het type SCM te kiezen , of de manier van hosten (Github ..)

**Comment by mylene** [comment]
Yep. Ben nu even naar een aantal alternatieven aan het kijken (zie Hipchat).

**Comment by DominiqueClaes** [comment]
Is ook wel handig als we bijvoorbeeld voor Jenkins kiezen, dat we al weten welke SCM we er aan kunnen koppelen. Je kan natuurlijk ook andere SCM's implementeren, maar dan wordt de scope te groot...
