### ISSUE TITLE
Continuous omgeving

### ISSUE THREAD

**Issue by mylene** [mylene/Alphabet#3]
Hier begint het m.i. interessant te worden, maar er moeten veel keuzes gemaakt worden
* CI tool: Jenkins om mee te beginnen? **beslissen of alternatief kiezen**
* Functionele tests: CucumberJVM met Selenium om te beginnen? **beslissen of alternatief kiezen**
* "Integratie testen": JMeter, SOAPUI om te beginnen? **beslissen of alternatief kiezen**
* CD tool: Jenkins CD plugin om te beginnen? **beslissen of alternatief kiezen**
* Repository: Nexus om te beginnen? **beslissen of alternatief kiezen**

Als deze keuzes zijn gemaakt, kunnen we een VM bouwen (nu even Vagrant, later kijken naar Docker?) **keuze maken**

**Comment by yuri-vlieks** [comment]
CI tool: Jenkins om mee te beginnen omdat dit ook in andere projecten interesant kan zijn/gebruikt wordt.
Functionele tests: CucumberJVM met Selenium lijkt mij prima als basis.
"Integratie testen": JMeter, SOAPUI , SoapUI lijkt mij voor sommige stukken interesant maar de vraag is dan om dit te doen via SoapUI projecten die we afvuren vanuit Java of meer in java zelf (als een Unit test).
CD tool: Heb ik even niet genoeg zicht op.
Repository: Nexus , gaan we dit dan ook zelf opzetten of alleen gebruiken ?

**Comment by DominiqueClaes** [comment]
Ik denk dat bovenstaande al een leuk begin is.
Er is een variant voor Cucumber, namelijk JBehave, die kan ook leuk zijn.

Voor de integratie testen is Arquillian misschien ook een leuk alternatief.
